import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./providers/provider";
import TopBar from "./components/topbar";
import FooterSite from "./components/footer";


const inter = Poppins({ subsets: ["latin"], weight: ["400"]});

export const metadata: Metadata = {
  title: "Bridge SA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <TopBar />
          {children}
          <FooterSite />
        </Provider>
      </body>
    </html>
  );
}
