import type { Metadata } from "next";
import { Poppins } from "next/font/google";


const inter = Poppins({ subsets: ["latin"], weight: ["400"]});

export const metadata: Metadata = {
    title: "Bridge SA",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
            {children}
        </body>
        </html>
    );
}
